[platformio]
default_envs = lolin_d32_pro_espadc_ina219

[common]
lib_deps =
  bblanchon/ArduinoJson@^7.0.4
  adafruit/Adafruit BME280 Library@^2.3.0
  adafruit/Adafruit INA219@^1.2.3
  adafruit/Adafruit ADS1X15@^2.5.0
  h2zero/NimBLE-Arduino@^1.4.2
build_flags =
  -DCORE_DEBUG_LEVEL=3

[env:lolin_d32_pro_espadc_ina219]
platform = espressif32
board = lolin_d32_pro
framework = arduino
monitor_speed = 115200
lib_deps = ${common.lib_deps}
build_flags =
  ${common.build_flags}
  -DUSE_ADS1115=0
  -DUSE_ACS71X_CURRENT=0

[env:lolin_d32_pro_espadc_acs71x]
platform = espressif32
board = lolin_d32_pro
framework = arduino
monitor_speed = 115200
lib_deps = ${common.lib_deps}
build_flags =
  ${common.build_flags}
  -DUSE_ADS1115=0
  -DUSE_ACS71X_CURRENT=1
  -DACS_CURRENT_SENS_MV_PER_A=90.0f
  -DACS_ZERO_V=1.65f

[env:lolin_d32_pro_ads1115_ina219]
platform = espressif32
board = lolin_d32_pro
framework = arduino
monitor_speed = 115200
lib_deps = ${common.lib_deps}
build_flags =
  ${common.build_flags}
  -DUSE_ADS1115=1
  -DUSE_ACS71X_CURRENT=0

[env:lolin_d32_pro_ads1115_acs71x]
platform = espressif32
board = lolin_d32_pro
framework = arduino
monitor_speed = 115200
lib_deps = ${common.lib_deps}
build_flags =
  ${common.build_flags}
  -DUSE_ADS1115=1
  -DUSE_ACS71X_CURRENT=1
  -DACS_CURRENT_SENS_MV_PER_A=90.0f
  -DACS_ZERO_V=1.65f
